### ISSUE TITLE
Teleportation enhancements

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/Bedrock#6]
Currently if someone for example has the name _ swaglord _ you must put the _ infront of the name to do /tp. Would be nice if you could just type /tp swag and you would tp to _ swaglord _

**Comment by dags-** [comment]
couldn't people just change their username to something not stupid? =/
you'd get problems when users with similar names are on, at which point you'd just end up using tab complete anyway

**Comment by Freshmilkymilk** [comment]
That's true, but might be good to have suggestions like warps do, for things like this.

**Comment by dags-** [comment]
With the tp command (and others that take a Player as an argument), Sponge automagically handles looking up and fetching the actual Player from the user input.
To do what you're suggesting, you'd need to re-write all these commands and process the raw input yourself, which imo is a lot of work for not a lot of gain.

With the warp command, Sponge isn't already doing any fancy processing on the user's input (ie the warp name), so there's no wheel re-inventing required to look up part-matches.
